### PR TITLE
Utility method to download weights #17

### PR DESCRIPTION
**Pull request by lukestanley**
Automatically downloads weights from Google Drive using 'gdown' if not found. 
Updates readme.
The dictionary in utils.py can be updated with new filenames and matching URLs if weights are added.
@orpatashnik @Skylion007

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by orpatashnik — APPROVED** [review]
Thanks! That helps a lot

**Comment by Skylion007** [comment]
@lukestanley The Colab Notebooks also need to be updated to remove the google drive authentication.

**Comment by lukestanley** [comment]
@Skylion007 unfortunately I'm not able to run the notebook right now, but if you are, it should be easy to copy paste, if you're up for it.

**Comment by Skylion007** [comment]
Seems to be a few issues with it at the moment. The gdown copy on the Colab is out of date so an explict pip install -U gdown is needed. Even then, seems like there are traffic issues that is preventing non-authenticated pathways to downloading the file. Ultimately we might need to keep the sign in system as a fallback.

**Pull request merged**
